
# Linear Regression with Python

Your neighbor is a real estate agent and wants some help predicting housing prices for regions in the USA. It would be great if you could somehow create a model for her that allows her to put in a few features of a house and returns back an estimate of what the house would sell for.

She has asked you if you could help her out with your new data science skills. You say yes, and decide that Linear Regression might be a good path to solve this problem!

Your neighbor then gives you some information about a bunch of houses in regions of the United States,it is all in the data set: USA_Housing.csv.

The data contains the following columns:

* 'Avg. Area Income': Avg. Income of residents of the city house is located in.
* 'Avg. Area House Age': Avg Age of Houses in same city
* 'Avg. Area Number of Rooms': Avg Number of Rooms for Houses in same city
* 'Avg. Area Number of Bedrooms': Avg Number of Bedrooms for Houses in same city
* 'Area Population': Population of city house is located in
* 'Price': Price that the house sold at
* 'Address': Address for the house

**Let's get started!**
## Check out the data
We've been able to get some data from your neighbor for housing prices as a csv set, let's get our environment ready with the libraries we'll need and then import the data!
### Import Libraries

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Check out the Data

In [11]:
df = pd.read_csv("https://drive.google.com/u/1/uc?id=1mZAYqKfk0UEOj0gXUMIsenkBXg3dl0TW&export=download")

In [12]:
df

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price,Address
0,79545.458574,5.682861,7.009188,4.09,23086.800503,1.059034e+06,"208 Michael Ferry Apt. 674\nLaurabury, NE 3701..."
1,79248.642455,6.002900,6.730821,3.09,40173.072174,1.505891e+06,"188 Johnson Views Suite 079\nLake Kathleen, CA..."
2,61287.067179,5.865890,8.512727,5.13,36882.159400,1.058988e+06,"9127 Elizabeth Stravenue\nDanieltown, WI 06482..."
3,63345.240046,7.188236,5.586729,3.26,34310.242831,1.260617e+06,USS Barnett\nFPO AP 44820
4,59982.197226,5.040555,7.839388,4.23,26354.109472,6.309435e+05,USNS Raymond\nFPO AE 09386
...,...,...,...,...,...,...,...
4995,60567.944140,7.830362,6.137356,3.46,22837.361035,1.060194e+06,USNS Williams\nFPO AP 30153-7653
4996,78491.275435,6.999135,6.576763,4.02,25616.115489,1.482618e+06,"PSC 9258, Box 8489\nAPO AA 42991-3352"
4997,63390.686886,7.250591,4.805081,2.13,33266.145490,1.030730e+06,"4215 Tracy Garden Suite 076\nJoshualand, VA 01..."
4998,68001.331235,5.534388,7.130144,5.44,42625.620156,1.198657e+06,USS Wallace\nFPO AE 73316
4999,65510.581804,5.992305,6.792336,4.07,46501.283803,1.298950e+06,"37778 George Ridges Apt. 509\nEast Holly, NV 2..."

# EDA

Let's create some simple plots to check out the data!

## Training a Linear Regression Model

Let's now begin to train out regression model! We will need to first split up our data into an X array that contains the features to train on, and a y array with the target variable, in this case the Price column. We will toss out the Address column because it only has text info that the linear regression model can't use.

### X and y arrays

In [13]:
X = df[[  # Dataframe
    'Avg. Area Income',
    'Avg. Area House Age',
    'Avg. Area Number of Rooms',
    'Avg. Area Number of Bedrooms',
    'Area Population'
]]

y = df['Price'] # Series

## Train Test Split

Now let's split the data into a training set and a testing set. We will train out model on the training set and then use the test set to evaluate the model.

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=73946)

In [15]:
X_train

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population
4979,82224.695006,5.434087,8.375708,3.12,57166.867510
1699,62902.255492,6.577966,6.711163,3.40,27321.032931
1823,75690.695439,6.241329,5.192788,4.05,46183.107365
4987,65729.222330,6.237787,6.860475,3.12,25573.854289
355,87266.340225,8.248959,7.234261,5.00,45161.187677
...,...,...,...,...,...
4314,72618.538462,5.160574,7.640127,4.46,37345.911723
4162,77453.479788,5.909818,7.640186,3.02,53100.278674
802,78846.270091,6.723852,7.647122,6.10,41261.188781
1002,71517.014241,7.905595,7.731386,5.02,40239.282575
4918,64909.041149,6.636131,9.054827,5.10,42180.647940

In [16]:
y_train

4979    1.823498e+06
1699    9.846723e+05
1823    1.308244e+06
4987    1.197073e+06
355     2.249123e+06
            ...
4314    1.420859e+06
4162    1.664148e+06
802     1.592665e+06
1002    1.734373e+06
4918    1.577850e+06
Name: Price, Length: 3750, dtype: float64

## Creating and Training the Model

In [17]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

LinearRegression()

In [18]:
model.predict(X_test)

array([ 472410.20088809,  919046.46975227, 1718603.09561626, ...,
       1205837.30542874, 1008841.93301946, 1151294.36787393])

In [19]:
y_test

3802    5.797101e+05
3313    8.422963e+05
3503    1.887529e+06
2971    1.322439e+06
2783    8.311688e+05
            ...
2470    1.340910e+06
1552    1.769485e+06
409     1.267443e+06
4549    1.003701e+06
273     1.310207e+06
Name: Price, Length: 1250, dtype: float64

In [20]:
X_evaluate = X_test.copy()
X_evaluate['truth'] = y_test
X_evaluate['predicted'] = model.predict(X_test)
X_evaluate

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,truth,predicted
3802,57876.995364,3.485870,5.961240,4.25,36800.460425,5.797101e+05,4.724102e+05
3313,68535.892232,5.155813,5.996543,2.00,32770.833622,8.422963e+05,9.190465e+05
3503,74764.543507,6.880993,8.005417,6.48,41102.071032,1.887529e+06,1.718603e+06
2971,87068.245131,6.427781,6.539577,4.12,16083.144423,1.322439e+06,1.344413e+06
2783,54920.063386,6.827613,6.188287,3.44,22835.584431,8.311688e+05,7.760209e+05
...,...,...,...,...,...,...,...
2470,89286.083249,5.407139,6.797126,2.45,26176.766149,1.340910e+06,1.405717e+06
1552,66803.016365,6.251245,8.750872,5.07,57970.242790,1.769485e+06,1.788179e+06
409,67710.112979,5.854378,8.482523,4.18,25222.462415,1.267443e+06,1.205837e+06
4549,77961.221935,5.043993,6.400132,2.33,23334.680279,1.003701e+06,1.008842e+06
273,79298.122008,7.188208,5.336841,3.44,15753.266638,1.310207e+06,1.151294e+06

## Model Evaluation

Let's evaluate the model by checking out it's coefficients and how we can interpret them.

In [21]:
pd.DataFrame(model.coef_)

               0
0      21.610980
1  166236.077975
2  120891.371493
3    1693.960751
4      15.329979

In [22]:
model.intercept_

-2649857.8156070337

Interpreting the coefficients:

- Holding all other features fixed, a 1 unit increase in **Avg. Area Income** is associated with an **increase of \$21.52**.
- Holding all other features fixed, a 1 unit increase in **Avg. Area House Age** is associated with an **increase of \$164883.28**.
- Holding all other features fixed, a 1 unit increase in **Avg. Area Number of Rooms** is associated with an **increase of \$122368.67**.
- Holding all other features fixed, a 1 unit increase in **Avg. Area Number of Bedrooms** is associated with an **increase of \$2233.80**.
- Holding all other features fixed, a 1 unit increase in **Area Population** is associated with an **increase of \$15.15**.

## Predictions from our Model

Let's grab predictions off our test set and see how well it did!

## Regression Evaluation Metrics


Here are three common evaluation metrics for regression problems:

**Mean Absolute Error** (MAE) is the mean of the absolute value of the errors:

$$\frac 1n\sum_{i=1}^n|y_i-\hat{y}_i|$$

**Mean Squared Error** (MSE) is the mean of the squared errors:

$$\frac 1n\sum_{i=1}^n(y_i-\hat{y}_i)^2$$

**Root Mean Squared Error** (RMSE) is the square root of the mean of the squared errors:

$$\sqrt{\frac 1n\sum_{i=1}^n(y_i-\hat{y}_i)^2}$$

Comparing these metrics:

- **MAE** is the easiest to understand, because it's the average error.
- **MSE** is more popular than MAE, because MSE "punishes" larger errors, which tends to be useful in the real world.
- **RMSE** is even more popular than MSE, because RMSE is interpretable in the "y" units.

All of these are **loss functions**, because we want to minimize them.

In [23]:
# MAE

(X_evaluate['truth'] - X_evaluate['predicted']).abs().mean()

82186.94927478804

In [24]:
# MSE

((X_evaluate['truth'] - X_evaluate['predicted']) ** 2).mean()

10372779675.692081

In [25]:
# RMSE

((X_evaluate['truth'] - X_evaluate['predicted']) ** 2).mean() ** 0.5

101846.8442107662

In [26]:
X_evaluate['truth']

3802    5.797101e+05
3313    8.422963e+05
3503    1.887529e+06
2971    1.322439e+06
2783    8.311688e+05
            ...
2470    1.340910e+06
1552    1.769485e+06
409     1.267443e+06
4549    1.003701e+06
273     1.310207e+06
Name: truth, Length: 1250, dtype: float64

In [27]:
X_evaluate['predicted']

3802    4.724102e+05
3313    9.190465e+05
3503    1.718603e+06
2971    1.344413e+06
2783    7.760209e+05
            ...
2470    1.405717e+06
1552    1.788179e+06
409     1.205837e+06
4549    1.008842e+06
273     1.151294e+06
Name: predicted, Length: 1250, dtype: float64

##Find **R Square**

The coefficient of determination, often denoted as R-squared (R2), is a statistical measure used to assess the goodness of fit of a regression model. R2 values range from -∞ to 1

R2 < 0 : The model perform worse then the baseline model ( = just give the average value as prediction)

R2 = 0 : the model does not explain any variability, and it's equivalent to using the baseline model

R2 = 1 : the model perfectly explains all the variability, and its predictions match the observed data points exactly

In [28]:
from sklearn.metrics import r2_score

r2_score(X_evaluate['truth'], X_evaluate['predicted'])

0.9127535847652193

In [29]:
model.score(X_test, y_test)

0.9127535847652193