# Exercise 2 - Ad click prediction

## 1. Reminder - General procedure of supervised learning

1. Prepare the data in which you fit into a model

    1. A table of feature
    2. A list of label

    The naming convention is like:
    - X to represent the features
    - y to represent the label
    - y hat (written ŷ ) to reprepsent the predicted outcome
    
2. Split the feature and label into training set and testing set.

    - X_train
    - y_train
    - X_test
    - y_test
    
    Note that we should have the same number of rows in X_train and y_train.  Also for X_test and y_test.

3. Use X_train and y_train to fit the model

4. Evaluate the result using X_test and y_test

## 2. Our task

In this project we will be working with a fake advertising data set, indicating whether or not a particular internet user clicked on an Advertisement on a company website. We will try to create a model that will predict whether or not they will click on an ad based off the features of that user.

This data set contains the following features:
```
* 'Daily Time Spent on Site': consumer time on site in minutes
* 'Age': cutomer age in years
* 'Area Income': Avg. Income of geographical area of consumer
* 'Daily Internet Usage': Avg. minutes a day consumer is on the internet
* 'Ad Topic Line': Headline of the advertisement
* 'City': City of consumer
* 'Male': Whether or not consumer was male
* 'Country': Country of consumer
* 'Timestamp': Time at which consumer clicked on Ad or closed window
* 'Clicked on Ad': 0 or 1 indicated clicking on Ad
```

### 2.1 Import libraries

It is tidier to put all import in one box.  You may import the important ones now, and add more later.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Optional
sns.set_style('whitegrid')

C:\Users\user\AppData\Local\Temp\ipykernel_22344\3544896185.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

### 2.2 Get the data and check it
**Read in the advertising.csv file and set it to a data frame called ad_data.**

In [3]:
ad_data = pd.read_csv('https://drive.google.com/u/1/uc?id=1cvmv0nj2RfFprJkG_lg6KV1-Wumcnrit&export=download')
ad_data

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Ad Topic Line,City,Male,Country,Timestamp,Clicked on Ad
0,68.95,35,61833.90,256.09,Cloned 5thgeneration orchestration,Wrightburgh,0,Tunisia,2016-03-27 00:53:11,0
1,80.23,31,68441.85,193.77,Monitored national standardization,West Jodi,1,Nauru,2016-04-04 01:39:02,0
2,69.47,26,59785.94,236.50,Organic bottom-line service-desk,Davidton,0,San Marino,2016-03-13 20:35:42,0
3,74.15,29,54806.18,245.89,Triple-buffered reciprocal time-frame,West Terrifurt,1,Italy,2016-01-10 02:31:19,0
4,68.37,35,73889.99,225.58,Robust logistical utilization,South Manuel,0,Iceland,2016-06-03 03:36:18,0
...,...,...,...,...,...,...,...,...,...,...
995,72.97,30,71384.57,208.58,Fundamental modular algorithm,Duffystad,1,Lebanon,2016-02-11 21:49:00,1
996,51.30,45,67782.17,134.42,Grass-roots cohesive monitoring,New Darlene,1,Bosnia and Herzegovina,2016-04-22 02:07:01,1
997,51.63,51,42415.72,120.37,Expanded intangible solution,South Jessica,1,Mongolia,2016-02-01 17:24:57,1
998,55.55,19,41920.79,187.95,Proactive bandwidth-monitored policy,West Steven,0,Guatemala,2016-03-24 02:35:54,0
999,45.01,26,29875.80,178.35,Virtual 5thgeneration emulation,Ronniemouth,0,Brazil,2016-06-03 21:43:21,1

**Check the head of ad_data**

In [ ]:
# Your code here

**Use info and describe() on ad_data**

In [ ]:
# Check the dataframe with .info()

In [ ]:
# Check the dataframe with .describe()

### 2.3 Exploratory Data Analysis

Let's use seaborn to explore the data!

Try recreating the plots shown below!

**Create a histogram of the Age**

Steps
1. Select the `Age` column
2. Call the `.hist()` function on it (adjust the chart using the `bins` keyword argument)

In [ ]:
# Your code here

**Create a jointplot showing Area Income versus Age.**

Steps:
1. Use the `.jointplot()` from `seaborn`
2. Put `'Age'` as `x`, `'Area Income'` as `y` and the dataframe as `data` of the keyword arguments of `jointplot()`

In [ ]:
# Your code here

**Create a jointplot of 'Daily Time Spent on Site' vs. 'Daily Internet Usage'**

Steps:
1. Use the `.jointplot()` from `seaborn`
2. Put `'Daily Time Spent on Site'` as `x`, `'Daily Internet Usage'` as `y` and the dataframe as `data` of the keyword arguments of `jointplot()`

In [ ]:
# Your code here

**Finally, create a pairplot with 2 colours - one for clicked on Ad, one for not clicked**

Steps:
1. Use the `.pairplot()` from `seaborn`
2. Put the dataframe as `data` of the keyword arguments of `jointplot()`
3. Also add `hue='Clicked on Ad'` to create two colours

In [ ]:
# Your code here

### 2.4 Logistic Regression

train test split, and train our model

**Split the data into training set and testing set using train_test_split**

In [5]:
# Your code here
from sklearn.model_selection import train_test_split

# Daily Time Spent on Site	Age	Area Income	Daily Internet Usage	Ad Topic Line	City	Male	Country	Timestamp	Clicked on Ad

X = ad_data[['Daily Time Spent on Site','Age','Area Income','Daily Internet Usage','Male']]
y = ad_data['Clicked on Ad']
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=101)

X_train

     Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  Male
968                     45.08   38     35349.26                125.27     0
205                     58.22   29     37345.24                120.90     0
231                     46.77   32     31092.93                136.40     1
147                     70.92   41     49995.63                108.16     1
531                     53.44   42     42907.89                108.17     1
..                        ...  ...          ...                   ...   ...
575                     48.86   54     53188.69                134.46     0
838                     44.13   40     33601.84                128.48     1
337                     75.32   28     59998.50                233.60     1
523                     67.94   43     68447.17                128.16     0
863                     76.64   39     66217.31                241.50     1

[750 rows x 5 columns]

**Train and fit a logistic regression model on the training set.**

In [8]:
# Your code here
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=99999)
model.fit(X_train, y_train)
pd.DataFrame(model.coef_,columns=['Daily Time Spent on Site','Age','Area Income','Daily Internet Usage','Male'])

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Male
0,-0.180382,0.145383,-0.000128,-0.06113,-0.462316

### 2.5 Predictions and Evaluations
**Now predict values for the testing data.**

In [16]:
# Your code here
y_pred = model.predict(X_test)
pd.DataFrame(y_test).value_counts()

Clicked on Ad
0                134
1                116
Name: count, dtype: int64

**Check the accuracy of our preduction**

$
\frac{\text{Number of correct prediction}}{\text{Sample  count}}
$

Instruction:

1. Calculate the accuracy

In [10]:
# Your code here
y_test == y_pred

545    True
298    True
109    True
837    True
194    True
       ...
971    True
267    True
772    True
172    True
491    True
Name: Clicked on Ad, Length: 250, dtype: bool

In [11]:
accuracy = (y_test == y_pred).mean()
#The definition of accuracy only applies to classification problem only. (Linear Regression uses MAE/ MSE/ RMSE/ R sq)
print(f"The accuracy of the prediction is {accuracy*100} percent.")

The accuracy of the prediction is 97.2 percent.

In [15]:
from sklearn.metrics import precision_recall_fscore_support

pd.DataFrame(precision_recall_fscore_support(y_test, y_pred),index=['precision','recall','fscore','support'])

                    0           1
precision    0.963504    0.982301
recall       0.985075    0.956897
fscore       0.974170    0.969432
support    134.000000  116.000000

In [17]:
#support means whether it is clicked or not and shows the count
pd.DataFrame(y_test).value_counts()

Clicked on Ad
0                134
1                116
Name: count, dtype: int64