# Exercise 1 - Classification

There are a few classification algorithms you can use, for example
- Naive Bayes
- Logistic Regression (Although named as regression, it is a classification tool)
- Random Forest
- XGBoost.

## 1. General Procedures for solving a supervised learning task

1. Prepare the data in which you fit into a model

    1. A table of feature
    2. A table of label

    The naming convention is like:
    - X to represent the features
    - y to represent the label
    - y hat (written ŷ ) to reprepsent the predicted outcome
    
2. Split the feature and label into training set and testing set.

    - X_train
    - y_train
    - X_test
    - y_test
    
    Note that we should have the same number of rows in X_train and y_train.  Also for X_test and y_test.

3. Use X_train and y_train to fit the model

4. Evaluate the result using X_test and y_test

## 2. Choice of model

There are a lot of models you can choose from in the python community.  Models are built on academic foundations.

`Scikit Learn` is where algorithms are implemented, ready to use.  It is recommended that to first **understand the algorithms** before we use them.

## 3. Let 's try

Our goal: Predict gender from one's height and weight

**Step 1**
Instruction:

1. Load `ML_L1.1_Gender_HW.csv` into a pandas dataframe.
2. Check that there are 3 columns `Gender`, `Height` and `Weight`
3. Check that there are 10000 samples

In [6]:
# Your code here

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt



df = pd.read_csv("https://drive.google.com/u/1/uc?id=17PldTm7CEH2PWyJjVdpAp3UyMOXC7bRi&export=download")
df
# df.describe()

      Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]

**Step 2**
Instruction:

Split our dataset using scikit-learn's `train_test_split`

https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html

You should be able to generate four variables:

- X_train
- y_train
- X_test
- y_test

*Note* Scikit learn and other ML packages are usually flexible enough to take various types of variables, including
- dataframe
- series
- numpy array
- simple list

In [8]:
# Your code here
X = df[['Height','Weight']]
y= df['Gender']

In [9]:
# Check the shape of each
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=101)

X_train

         Height      Weight
4492  67.252841  174.175001
966   73.187949  204.103817
7002  61.991074  131.410732
8374  65.394498  146.209595
3075  72.289596  213.896690
...         ...         ...
599   72.342184  215.858234
5695  62.781048  135.628791
8006  59.917631  118.463414
1361  70.878633  194.073975
1547  74.709612  207.243854

[7500 rows x 2 columns]

**Step 3**

With our Xs and ys ready, we can load them into a model.
Let 's try the LogisticRegression model as our start.
```python
from sklearn.linear_model import LogisticRegression
```

https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

Instruction:
1. Create a `LogisticRegression` model
2. Call the `.fit()` function of the model, here's where all the training happens

In [21]:
# Your code here
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)
pd.DataFrame(model.coef_,columns=['Height','Weight'])

     Height    Weight
0 -0.486975  0.200274

**Step 4**

Now our model is ready, we can do some prediction with it.

Instruction:

1. Call the `.predict()` function of our model, passing in our `X_test`.
2. Save the result into `y_pred`

In [27]:
# Your code here
y_pred = model.predict(X_test)
pd.DataFrame(y_pred).value_counts()

0
Female    1262
Male      1238
Name: count, dtype: int64

**Step 5**

Let's see how accurate is our preduction.

Accuracy is defined as

$
\frac{\text{Number of correct prediction}}{\text{Sample  count}}
$

Instruction:

1. Calculate the accuracy

In [32]:
# Your code here

2500

In [33]:
y_test == y_pred

6676     True
6421     True
9834     True
8492     True
9982    False
        ...
9099     True
5270     True
5644     True
6360     True
9697     True
Name: Gender, Length: 2500, dtype: bool

In [36]:
accuracy = (y_test == y_pred).mean()
#The definition of accuracy only applies to classification problem only. (Linear Regression uses MAE/ MSE/ RMSE/ R sq)
print(f"The accuracy of the prediction is {accuracy*100} percent.")

The accuracy of the prediction is 91.16 percent.